version: '3'

services:
  db:
    environment:
      - POSTGRES_USER=email_marketing
      - POSTGRES_PASSWORD=demo123
      - POSTGRES_DB=demo
  web:
    build: .
    environment:
      - POSTGRES_USER=email_marketing
      - POSTGRES_PASSWORD=demo123
      - POSTGRES_DATABASE=demo
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    volumes:
      - .:/code
  celery:
    build: .
    volumes:
      - .:/code
    environment:
      - POSTGRES_USER=email_marketing
      - POSTGRES_PASSWORD=demo123
      - POSTGRES_DATABASE=demo
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432

volumes:
  pgdata:
