# Generated by Django 2.2.7 on 2019-11-22 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flyps_login', models.CharField(blank=True, max_length=255, null=True)),
                ('flyps_password', models.CharField(blank=True, max_length=255, null=True)),
                ('header_email', models.CharField(blank=True, max_length=255, null=True)),
                ('header_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
